name: Build and Release App

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build app
        run: |
          pyinstaller main.spec

      - name: Archive windows artifacts
        if: ${{ matrix.os == 'windows-latest' }}
        run: tar -cvzf histobcad-windows.tar.gz dist/HistoBCAD.exe

      - name: Archive ubuntu artifacts
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: tar -cvzf histobcad-linux.tar.gz dist/HistoBCAD

      - name: Archive macos artifacts
        if: ${{ matrix.os == 'macos-latest' }}
        run: tar -cvzf histobcad-macos.tar.gz dist/HistoBCAD

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            histobcad-windows.tar.gz
            histobcad-linux.tar.gz
            histobcad-macos.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-build
          path: builds/ubuntu-latest/
      - uses: actions/download-artifact@v4
        with:
          name: windows-latest-build
          path: builds/windows-latest/
      - uses: actions/download-artifact@v4
        with:
          name: macos-latest-build
          path: builds/macos-latest/

      - name: Generate app version
        id: version
        shell: bash
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          COMMIT=$(git rev-parse --short HEAD)
          if [ "$(git describe --tags --exact-match 2>/dev/null || echo '')" = "$TAG" ]; then
            VERSION="$TAG"
          else
            VERSION="${TAG}-${COMMIT}"
          fi
          echo "version=${VERSION}" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.version }}
          release_name: ${{ env.version }}
          body: |
            Automated release created by GitHub Actions.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets (ubuntu)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: builds/ubuntu-latest/histobcad-linux.tar.gz
          asset_name: histobcad-linux.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets (windows)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: builds/windows-latest/histobcad-windows.tar.gz
          asset_name: histobcad-windows.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets (macos)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: builds/macos-latest/histobcad-macos.tar.gz
          asset_name: histobcad-macos.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}